# vits_tts_plugin - 自动生成的配置文件
# 基于 artrajz-vits-simple-api 的文本转语音插件，支持多种语言和音色。

# 插件基本配置
[plugin]

# 是否启用插件
enabled = true


# 组件启用控制
[components]

# 是否启用Action组件
action_enabled = true

# 是否启用Command组件
command_enabled = true


# VITS API配置
[vits]

# VITS API地址
api_url = "https://artrajz-vits-simple-api.hf.space/voice/vits"

# 默认音色ID
default_voice_id = "0"

# 默认语言（zh/en/ja等）
language = "zh"

# API请求超时时间（秒）
timeout = 30

# 最大文本长度限制
max_text_length = 500

# API调用失败重试次数
retry_count = 2

# 音频文件格式
audio_format = "wav"


